/**
 * Conformance suite: loads ../spec/vectors.json (generated by the Python
 * reference) and checks this implementation reproduces every golden vector
 * byte-for-byte. Data-driven and tolerant: unknown vector sections and
 * artifact kinds are skipped with a log line rather than crashing, so the
 * Python side can grow new cases without breaking this runner.
 *
 * Run: npm test   (or: npm run conformance)
 */

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

import {
  AgentCard,
  addressFromSigningKey,
  base58Encode,
  bytesToHex,
  canonicalJson,
  canonicalTimestamp,
  concatBytes,
  decodeSignature,
  didDocument,
  ed25519PublicFromSeed,
  ed25519Sign,
  ed25519Verify,
  hexToBytes,
  KeyPair,
  keyCommitment,
  parseTimestamp,
  sha256Hex,
  signingInput,
  signingKeyFromAddress,
} from "../src/index.js";

const here = dirname(fileURLToPath(import.meta.url));
// dist/test/ -> repo spec/ is three levels up from the compiled test file.
const vectorsPath = join(here, "..", "..", "..", "spec", "vectors.json");
const vectors = JSON.parse(readFileSync(vectorsPath, "utf-8"));

// Fixed seeds from spec/generate_vectors.py. If the generator ever changes
// its seeds, the address assertions below fail loudly rather than silently.
const range = (start: number, end: number) =>
  new Uint8Array(Array.from({ length: end - start }, (_, i) => start + i));
const SEED_A = range(0, 32);
const SEED_B = range(32, 64);
const SEED_C = range(64, 96);
const AGREEMENT_SEED = range(96, 128);

async function seedKeys(seed: Uint8Array): Promise<KeyPair> {
  return KeyPair.fromSeeds(seed, AGREEMENT_SEED);
}

test("canonical_json vectors", () => {
  for (const [i, vector] of (vectors.canonical_json ?? []).entries()) {
    assert.equal(
      bytesToHex(canonicalJson(vector.input)),
      vector.expected_hex,
      `canonical_json[${i}]`
    );
  }
});

test("base58 vectors", () => {
  for (const [i, vector] of (vectors.base58 ?? []).entries()) {
    assert.equal(base58Encode(hexToBytes(vector.input_hex)), vector.expected, `base58[${i}]`);
  }
});

test("ed25519 vectors: public derivation, address, deterministic signature", async () => {
  const ed = vectors.ed25519;
  const seed = hexToBytes(ed.seed_hex);
  const publicKey = await ed25519PublicFromSeed(seed);
  assert.equal(bytesToHex(publicKey), ed.public_hex);
  assert.equal(addressFromSigningKey(publicKey), ed.address);
  const signature = await ed25519Sign(seed, hexToBytes(ed.message_hex));
  assert.equal(bytesToHex(signature), ed.signature_hex);
  assert.equal(
    await ed25519Verify(publicKey, hexToBytes(ed.message_hex), hexToBytes(ed.signature_hex)),
    true
  );
});

test("canonical_timestamp vectors", () => {
  for (const [i, vector] of (vectors.canonical_timestamp ?? []).entries()) {
    assert.equal(
      canonicalTimestamp(parseTimestamp("input", vector.input)),
      vector.expected,
      `canonical_timestamp[${i}]`
    );
  }
});

test("signing_input vectors", () => {
  for (const [i, vector] of (vectors.signing_input ?? []).entries()) {
    assert.equal(
      bytesToHex(signingInput(vector.context, vector.payload)),
      vector.expected_hex,
      `signing_input[${i}]`
    );
  }
});

test("key_commitment vector", async () => {
  const kc = vectors.key_commitment;
  assert.equal(await keyCommitment(hexToBytes(kc.signing_public_hex)), kc.expected);
});

test("fixed seeds still derive the vector addresses", async () => {
  const addresses = vectors.addresses ?? {};
  const derived = {
    a: addressFromSigningKey(await ed25519PublicFromSeed(SEED_A)),
    b: addressFromSigningKey(await ed25519PublicFromSeed(SEED_B)),
    c: addressFromSigningKey(await ed25519PublicFromSeed(SEED_C)),
  };
  assert.deepEqual(derived, addresses);
});

/** Which seed signs each artifact kind, and which payload field certifies it. */
const ARTIFACT_RULES: Record<string, { seed: Uint8Array; signerField: string }> = {
  agent_card: { seed: SEED_A, signerField: "address" },
  delegation: { seed: SEED_B, signerField: "issuer" },
  revocation: { seed: SEED_B, signerField: "issuer" },
  key_revocation: { seed: SEED_A, signerField: "issuer" },
  inception: { seed: SEED_A, signerField: "address" },
  key_rotation: { seed: SEED_A, signerField: "previous" },
  challenge_response: { seed: SEED_A, signerField: "address" },
  agent_card_critical: { seed: SEED_A, signerField: "address" },
  delegation_critical: { seed: SEED_B, signerField: "issuer" },
};

test("artifact vectors: signing_input, signature reproduction, verification", async () => {
  for (const [kind, artifact] of Object.entries(vectors.artifacts ?? {}) as [string, any][]) {
    const rule = ARTIFACT_RULES[kind];
    if (!rule) {
      console.log(`SKIP unknown artifact vector kind: ${kind}`);
      continue;
    }
    const input = signingInput(artifact.context, artifact.payload);
    assert.equal(bytesToHex(input), artifact.signing_input_hex, `${kind}.signing_input`);

    // Ed25519 is deterministic: re-signing with the fixed seed must reproduce
    // the exact vector signature.
    const keys = await seedKeys(rule.seed);
    const { base64Encode } = await import("../src/bytes.js");
    assert.equal(base64Encode(await keys.sign(input)), artifact.signature_b64, `${kind}.signature`);

    // And the signature must verify against the key the artifact certifies.
    const signerAddress = artifact.payload[rule.signerField];
    const publicKey = signingKeyFromAddress(signerAddress);
    assert.equal(
      await ed25519Verify(publicKey, input, decodeSignature(artifact.signature_b64)),
      true,
      `${kind}.verify`
    );

    if (artifact.digest !== undefined) {
      // Delegation digest: sha256(signing_input || decoded_signature) hex.
      const digest = await sha256Hex(
        concatBytes(input, decodeSignature(artifact.signature_b64))
      );
      assert.equal(digest, artifact.digest, `${kind}.digest`);
    }
  }
});

test("agent_card vector verifies through the AgentCard class", async () => {
  const artifact = vectors.artifacts?.agent_card;
  if (!artifact) return;
  const card = AgentCard.fromJSON({ ...artifact.payload, signature: artifact.signature_b64 });
  await card.verify();
  assert.deepEqual(card.payload(), artifact.payload);
});

test("critical vectors: byte-exact, rejected unless the extension is understood", async () => {
  const cardVector = vectors.artifacts?.agent_card_critical;
  if (cardVector) {
    const card = AgentCard.fromJSON({
      ...cardVector.payload,
      signature: cardVector.signature_b64,
    });
    assert.deepEqual(card.payload(), cardVector.payload);
    await assert.rejects(card.verify(), /critical/);
    await card.verify(Object.keys(card.extra)); // understood -> accepted
  }
  const delegationVector = vectors.artifacts?.delegation_critical;
  if (delegationVector) {
    const { Delegation } = await import("../src/delegation.js");
    const delegation = Delegation.fromJSON({
      ...delegationVector.payload,
      signature: delegationVector.signature_b64,
    });
    assert.deepEqual(delegation.payload(), delegationVector.payload);
    const past = new Date("2026-01-15T00:00:00Z"); // inside the vector's window
    await assert.rejects(delegation.verify(past), /critical/);
    await delegation.verify(past, { understoodExtensions: Object.keys(delegation.extra) });
  }
});

test("did_document vector", async () => {
  const dd = vectors.did_document;
  if (!dd) return;
  const artifact = vectors.artifacts?.agent_card;
  const card = AgentCard.fromJSON({ ...artifact.payload, signature: artifact.signature_b64 });
  const { addressToDid } = await import("../src/did.js");
  assert.equal(addressToDid(dd.address), dd.did);
  assert.deepEqual(didDocument(card), dd.document);
});

test("report unknown top-level vector sections", () => {
  const known = new Set([
    "version",
    "note",
    "domain",
    "canonical_json",
    "base58",
    "ed25519",
    "canonical_timestamp",
    "signing_input",
    "key_commitment",
    "artifacts",
    "did_document",
    "addresses",
  ]);
  for (const key of Object.keys(vectors)) {
    if (!known.has(key)) console.log(`SKIP unknown vector section: ${key}`);
  }
  assert.equal(vectors.domain, "fg-agent-id/v1");
});
